name: Clone & Push to Empty Repo

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository (e.g. https://github.com/immortalwrt/immortalwrt.git)'
        required: true
      source_branch:
        description: 'Source branch to clone (e.g. v24.10.2)'
        required: true
      target_repo:
        description: 'Target repository to push to (e.g. https://github.com/youruser/yourrepo.git)'
        required: true
      target_branch:
        description: 'Target branch to push to (e.g. main)'
        required: true

jobs:
  push-to-empty-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Clone source repo (full history)
      run: |
        git clone --branch "${{ github.event.inputs.source_branch }}" "${{ github.event.inputs.source_repo }}" source-repo

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Force push to target empty repo
      env:
        TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        cd source-repo

        # Replace https://... with x-access-token
        CLEAN_URL="${{ github.event.inputs.target_repo#https:// }}"
        echo "Target remote: https://x-access-token@${CLEAN_URL}"

        # Set new remote pointing to target repo
        git remote add new-origin "https://x-access-token:${TOKEN}@${CLEAN_URL}"

        # Push full history forcibly to target branch
        git push --force new-origin HEAD:${{ github.event.inputs.target_branch }}
