name: Clone & Push to Empty Repo

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository (e.g. https://github.com/immortalwrt/immortalwrt.git)'
        required: true
      source_branch:
        description: 'Source branch to clone (e.g. v24.10.2)'
        required: true
      target_repo:
        description: 'Target repository to push to (e.g. https://github.com/youruser/yourrepo.git)'
        required: true
      target_branch:
        description: 'Target branch to push to (e.g. main)'
        required: true

jobs:
  push-to-empty-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Clone source repo (full history)
      run: |
        git clone --branch "${{ github.event.inputs.source_branch }}" "${{ github.event.inputs.source_repo }}" source-repo

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Force push to target empty repo
      env:
        TOKEN: ${{ secrets.PUSH_TOKEN }}
        TARGET_REPO: ${{ github.event.inputs.target_repo }}
        TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
      run: |
        cd source-repo

        # Convert target_repo to authenticated URL
        CLEAN_URL="${TARGET_REPO/https:\/\/github.com\//}"
        AUTH_URL="https://x-access-token:${TOKEN}@github.com/${CLEAN_URL}"

        echo "Pushing to: ${AUTH_URL} on branch ${TARGET_BRANCH}"

        git remote add target "${AUTH_URL}"
        git push --force target HEAD:${TARGET_BRANCH}
